### ISSUE TITLE
Unsafe instantiation of arrays

### ISSUE THREAD

**Issue by GrabYourPitchforks** [adamsitnik/SafePayloadReader#4]
There are a few places in the code where an untrusted count / length / etc. value is used as a length argument for array creation. This allows trivial DoS via an untrusted payload specifying very large lengths but never providing any data after the length value.

https://github.com/adamsitnik/SafePayloadReader/blob/cfb7ac5e388fcfbe4e24fd034c282509b0a283aa/System.Runtime.Serialization.BinaryFormat/Records/ArraySinglePrimitiveRecord.cs#L61-L71

https://github.com/adamsitnik/SafePayloadReader/blob/cfb7ac5e388fcfbe4e24fd034c282509b0a283aa/System.Runtime.Serialization.BinaryFormat/Infos/ClassInfo.cs#L34-L35

https://github.com/adamsitnik/SafePayloadReader/blob/cfb7ac5e388fcfbe4e24fd034c282509b0a283aa/System.Runtime.Serialization.BinaryFormat/Infos/MemberTypeInfo.cs#L22-L24

https://github.com/adamsitnik/SafePayloadReader/blob/cfb7ac5e388fcfbe4e24fd034c282509b0a283aa/System.Runtime.Serialization.BinaryFormat/Records/ArraySingleStringRecord.cs#L32

https://github.com/adamsitnik/SafePayloadReader/blob/cfb7ac5e388fcfbe4e24fd034c282509b0a283aa/System.Runtime.Serialization.BinaryFormat/Records/BinaryArrayRecord.cs#L39-L47

**Comment by adamsitnik** [comment]
What would be the proper fix? Allocate Lists with max capacity set to the provided length and add items to the list?
